/* SPDX-License-Identifier: GPL-3.0-or-later */
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const script=fs.readFileSync(path.join(__dirname,'../chatgpt-dom.js'),'utf8');
function harness(body){const dom=new JSDOM('<body>'+body+'</body>',{runScripts:'outside-only'});dom.window.eval(script);return {w:dom.window,d:dom.window.document,api:dom.window.LatexIslandsChatGPT,close:()=>dom.window.close()};}
// A structural fixture of the public September 26 renderer, with synthetic content.
const modern=`<main data-app-shell-main-surface="browser"><div data-app-action-timeline-scroll style="display:flex;flex-direction:column-reverse;overflow-y:auto"><div data-chatgpt-conversation-selection-target><div data-turn-key="prompt-0"><div data-content-search-turn-key="fallback-turn-0">
<div data-chatgpt-search-unit-key="fallback-turn-0:0:user" data-chatgpt-search-message-ids="prompt-0"><img alt="Attachment" src="data:,fixture"><div data-content-search-unit-key="fallback-turn-0:0:user"></div></div>
<div data-chatgpt-search-unit-key="fallback-turn-0:2:assistant" data-chatgpt-search-message-ids="answer-0 answer-0"><h4 class="sr-only" data-conversation-role="assistant">ChatGPT said:</h4><div data-chatgpt-selection-message-id="answer-0"><div data-markdown-text-style="assistant-message"><div><div data-markdown-copy="code-block"><div data-markdown-copy="exclude"><svg></svg><div>tikz</div><button>Copy</button></div><div dir="ltr"><code><span>\\begin{tikzpicture}\n% Keep the newline\n\\draw (0,0)--(1,1);\n\\end{tikzpicture}</span></code></div></div></div></div></div></div>
<div class="turn-action-controls"><button>Copy response</button></div>
</div></div></div></div></main>`;
test('September renderer: canonical messages, image-only prompt, stable IDs, code and turn actions',()=>{const h=harness(modern);try{
 const messages=h.api.getMessages();assert.equal(messages.length,2);assert.deepEqual(Array.from(messages,h.api.role),['user','assistant']);assert.deepEqual(Array.from(messages,h.api.messageId),['prompt-0','answer-0']);assert.deepEqual(Array.from(messages,h.api.turnIndex),[0,0]);
 const block=h.api.getCodeBlocks(messages[1])[0];assert.equal(h.api.getCodeBlocks(messages[1]).length,1);assert.equal(h.api.language(block),'tikz');assert.match(h.api.source(block),/newline\n\\draw/);assert.equal(h.api.getMessage(block),messages[1]);assert.equal(h.api.getReplyActions(messages[1]),h.d.querySelector('.turn-action-controls'));assert.equal(h.api.getReplyActions(messages[0]),null);
 assert.equal(h.api.getScrollRoot(),h.d.querySelector('[data-app-action-timeline-scroll]'));assert.equal(h.api.getViewport(block),h.api.getScrollRoot());
}finally{h.close();}});
test('legacy messages and CodeMirror remain supported without double counting nested pre',()=>{const h=harness('<main><article data-testid="conversation-turn-0"><div data-message-author-role="assistant" data-message-id="a"><pre><span class="font-medium">tikz</span><pre class="cm-content"><div class="cm-line">one</div><div class="cm-line">two</div></pre></pre></div></article></main>');try{const [a]=h.api.getMessages();const blocks=h.api.getCodeBlocks(a);assert.equal(blocks.length,1);assert.equal(h.api.source(blocks[0]),'one\ntwo');assert.equal(h.api.turnIndex(a),0);assert.equal(h.api.messageId(a),'a');}finally{h.close();}});
test('hidden stale roots and own PDF previews never enter active messages',()=>{const h=harness('<main hidden><div data-message-author-role="assistant">Stale</div></main><main><div data-message-author-role="user">Current</div><div style="display:none"><div data-message-author-role="assistant">Branch</div></div><div class="li-pdf-root"><div data-message-author-role="assistant">Copy</div></div></main>');try{assert.equal(h.api.getConversationRoot(),h.d.querySelectorAll('main')[1]);assert.equal(h.api.getMessages().length,1);assert.equal(h.api.role(h.api.getMessages()[0]),'user');}finally{h.close();}});
test('header selects visible native actions, ignoring measurement clones and hidden legacy header',()=>{const h=harness('<header id="conversation-header-actions" hidden></header><main><div data-app-shell-main-titlebar="true" aria-hidden="true"><div data-app-shell-header-obstacle><button>Clone</button></div></div><div data-app-shell-main-titlebar="true"><div data-app-shell-header-obstacle><div><div id="actions"><span><button>Share</button></span><button>More</button><div class="li-export"><button>Export</button></div></div></div></div></div></main>');try{assert.equal(h.api.getHeaderActions(),h.d.getElementById('actions'));}finally{h.close();}});
test('a late semantic marker is discovered without caching old roles',()=>{const h=harness('<main><div id="late"><div data-chatgpt-selection-message-id="a"><div data-markdown-text-style="assistant-message"></div></div></div></main>');try{assert.equal(h.api.getMessages().length,1);const late=h.d.getElementById('late');late.setAttribute('data-chatgpt-search-unit-key','fallback-turn-4:2:assistant');assert.equal(h.api.getMessages().length,1);assert.equal(h.api.getMessages()[0],late);assert.equal(h.api.turnIndex(late),4);assert.ok(h.api.observedAttributes.includes('data-chatgpt-search-unit-key'));}finally{h.close();}});
test('streaming checks the whole new turn but ignores our busy export controls',()=>{const h=harness(modern);try{const a=h.api.getMessages()[1],turn=a.closest('[data-content-search-turn-key]');assert.equal(h.api.isStreaming(a),false);const status=h.d.createElement('div');status.setAttribute('aria-busy','true');turn.append(status);assert.equal(h.api.isStreaming(a),true);status.className='li-export-reply';assert.equal(h.api.isStreaming(a),false);}finally{h.close();}});
test('streaming recognizes a hidden original after the host overwrites its classes',()=>{const h=harness(modern);try{const a=h.api.getMessages()[1],block=h.api.getCodeBlocks(a)[0],status=h.d.createElement('span');status.setAttribute('aria-busy','true');block.append(status);block.setAttribute('data-latex-islands-hidden','true');block.style.display='none';block.className='host-replaced-class';assert.equal(h.api.isStreaming(a),true);block.removeAttribute('data-latex-islands-hidden');assert.equal(h.api.isStreaming(a),false);}finally{h.close();}});
test('streaming leaves completed prompts exportable and ignores hidden status markers',()=>{const h=harness(modern);try{const [u,a]=h.api.getMessages(),status=h.d.createElement('span');status.setAttribute('aria-busy','true');a.append(status);assert.equal(h.api.isStreaming(u),false);assert.equal(h.api.isStreaming(a),true);status.hidden=true;assert.equal(h.api.isStreaming(a),false);status.hidden=false;status.style.display='none';assert.equal(h.api.isStreaming(a),false);}finally{h.close();}});
test('live September composer stop control keeps partial code streaming without old attributes',()=>{const h=harness(modern+'<div data-chatgpt-composer><div data-composer-footer-responsive><button aria-label="Arrêter">■</button></div></div>');try{const [u,a]=h.api.getMessages();assert.equal(h.api.isStreaming(a),true);assert.equal(h.api.isStreaming(u),false);h.d.querySelector('[aria-label="Arrêter"]').remove();assert.equal(h.api.isStreaming(a),false);}finally{h.close();}});
test('visibility checks reuse shared ancestors without caching between traversals',()=>{const h=harness('<main>'+Array.from({length:100},(_,i)=>'<article data-message-author-role="assistant">'+i+'</article>').join('')+'</main>');try{let reads=0;const original=h.w.getComputedStyle;h.w.getComputedStyle=(...args)=>{reads++;return original(...args);};assert.equal(h.api.getMessages().length,100);assert(reads<220,'ancestor styles are read once per traversal');h.d.querySelector('main').hidden=true;assert.equal(h.api.getMessages().length,0);}finally{h.close();}});
